version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - dogsled
    - errcheck
    - errorlint
    - exhaustive
    - gochecknoglobals
    - gochecknoinits
    - gocritic
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    misspell:
      locale: US
    nolintlint:
      require-specific: true
    prealloc:
      simple: true
      range-loops: true
      for-loops: true
    revive:
      rules:
        - name: var-naming
          disabled: true

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
formatters:
  enable:
    - gofmt
    - goimports
