// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol.proto

package internal

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	v1 "go.temporal.io/api/common/v1"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Frame struct {
	Messages             []*Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Frame) Reset()         { *m = Frame{} }
func (m *Frame) String() string { return proto.CompactTextString(m) }
func (*Frame) ProtoMessage()    {}
func (*Frame) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0}
}

func (m *Frame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Frame.Unmarshal(m, b)
}
func (m *Frame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Frame.Marshal(b, m, deterministic)
}
func (m *Frame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Frame.Merge(m, src)
}
func (m *Frame) XXX_Size() int {
	return xxx_messageInfo_Frame.Size(m)
}
func (m *Frame) XXX_DiscardUnknown() {
	xxx_messageInfo_Frame.DiscardUnknown(m)
}

var xxx_messageInfo_Frame proto.InternalMessageInfo

func (m *Frame) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

// Single communication message.
type Message struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// command name (if any)
	Command string `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	// command options in json format.
	Options []byte `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	// error response.
	Error *Error `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	// invocation or result payloads.
	Payloads             *v1.Payloads `protobuf:"bytes,5,opt,name=payloads,proto3" json:"payloads,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{1}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Message) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *Message) GetOptions() []byte {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *Message) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Message) GetPayloads() *v1.Payloads {
	if m != nil {
		return m.Payloads
	}
	return nil
}

// Generalized error
type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{2}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Frame)(nil), "temporal.roadrunner.internal.Frame")
	proto.RegisterType((*Message)(nil), "temporal.roadrunner.internal.Message")
	proto.RegisterType((*Error)(nil), "temporal.roadrunner.internal.Error")
}

func init() { proto.RegisterFile("protocol.proto", fileDescriptor_2bc2336598a3f7e0) }

var fileDescriptor_2bc2336598a3f7e0 = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xc1, 0x4a, 0xfc, 0x30,
	0x10, 0xc6, 0x49, 0xb7, 0xfd, 0xef, 0xfe, 0xb3, 0xb2, 0x87, 0x9c, 0x82, 0x78, 0x08, 0x15, 0xa1,
	0x78, 0x48, 0xd9, 0xf5, 0x24, 0x78, 0xf1, 0xa0, 0xa0, 0x20, 0x48, 0xde, 0x60, 0x6c, 0x82, 0x04,
	0xda, 0x4c, 0x48, 0xeb, 0x82, 0x2f, 0xe8, 0x73, 0x49, 0xd2, 0x74, 0xbd, 0xed, 0x6d, 0x26, 0xf3,
	0xfb, 0x26, 0xdf, 0x37, 0x74, 0xe7, 0x03, 0x4e, 0xd8, 0x61, 0x2f, 0x53, 0xc1, 0xae, 0x26, 0x33,
	0x78, 0x0c, 0xd0, 0xcb, 0x80, 0xa0, 0xc3, 0x97, 0x73, 0x26, 0x48, 0xeb, 0x26, 0x13, 0x1c, 0xf4,
	0x97, 0xb7, 0x09, 0x6a, 0x17, 0xa6, 0x05, 0x6f, 0xdb, 0x0e, 0x87, 0x01, 0x5d, 0x7b, 0xdc, 0xb7,
	0x83, 0x19, 0x47, 0xf8, 0x34, 0xf3, 0xa6, 0xfa, 0x95, 0x56, 0xcf, 0x01, 0x06, 0xc3, 0x1e, 0xe9,
	0x26, 0x4f, 0x46, 0x4e, 0xc4, 0xaa, 0xd9, 0x1e, 0x6e, 0xe4, 0xb9, 0x5f, 0xe4, 0xdb, 0x4c, 0xab,
	0x93, 0xac, 0xfe, 0x21, 0x74, 0x9d, 0x5f, 0xd9, 0x8e, 0x16, 0x56, 0x73, 0x22, 0x48, 0x53, 0xaa,
	0xc2, 0x6a, 0xc6, 0xe9, 0x3a, 0x5a, 0x00, 0xa7, 0x79, 0x21, 0x48, 0xf3, 0x5f, 0x2d, 0x6d, 0x9c,
	0xa0, 0x9f, 0x2c, 0xba, 0x91, 0xaf, 0x04, 0x69, 0x2e, 0xd4, 0xd2, 0xb2, 0x7b, 0x5a, 0x99, 0x10,
	0x30, 0xf0, 0x52, 0x90, 0x66, 0x7b, 0xb8, 0x3e, 0xef, 0xe7, 0x29, 0xa2, 0x6a, 0x56, 0xb0, 0x07,
	0xba, 0xf1, 0xf0, 0xdd, 0x23, 0xe8, 0x91, 0x57, 0x49, 0x2d, 0xfe, 0xd4, 0xe0, 0xad, 0x9c, 0xef,
	0x21, 0x8f, 0x7b, 0xf9, 0x9e, 0x39, 0x75, 0x52, 0xd4, 0x2f, 0xb4, 0x4a, 0xdb, 0x18, 0xa3, 0x65,
	0x87, 0xda, 0xa4, 0x1c, 0x95, 0x4a, 0x75, 0xf4, 0x9b, 0x13, 0x2f, 0x49, 0x72, 0x1b, 0x69, 0x0d,
	0x13, 0xe4, 0x18, 0xa9, 0xfe, 0xf8, 0x97, 0xce, 0x7c, 0xf7, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x16,
	0x0f, 0xc1, 0xf3, 0xc2, 0x01, 0x00, 0x00,
}
